name: Compress Images

on:
  push:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.svg'

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compress Images
        uses: id-top/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Commit Optimized Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: compress images automatically [skip ci]"
